RANDOMWALK-17: controller mock 1 version
ru-random-walk/chat-service pull request #1
Opened 2024-09-22 16:38 UTC by maksmolchdmitr

2024-09-24 12:15 UTC, kryakobess requested changes

2024-09-24 12:15 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/controller/MessageController.java
> +            @RequestParam @Schema(example = "0") long pageNumber,
это же подставляется через Pageable интерфейс

2024-09-24 12:15 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/dto/request/MessageRequest.java
> +public record MessageRequest(
Конструкторы неудобно читать без ide. Лучше всякие дтошки заправлять через Builder, если надо руками это сделать

2024-09-24 12:15 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/dto/request/MessageRequest.java
> +public record MessageRequest(
Поэтому добавь сюда билдер)

2024-09-24 12:15 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/controller/MessageController.java
> +                        UUID.randomUUID(),
Это тоже лучше через билдер сделать (а лучше через мапстракт если там сущность будет), но сейчас пофиг так как это заглушка.

2024-09-24 12:15 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/dto/response/Chat.java
> +public record Chat(
Builder

2024-09-24 12:15 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/dto/response/Message.java
> +public record Message(
Builder

2024-09-24 12:15 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/dto/response/Page.java
> +public record Page<T>(
Есть же стандартные джавовые Page и PageImpl вроде, зачем свое городить

2024-09-24 12:15 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/dto/response/message/Payload.java
> +package ru.random.walk.chat_service.dto.response.message;
Давай лучше перенесем в пакет payload, чтобы все по домену лежало

2024-09-24 12:15 UTC, kryakobess commented on build.gradle
> +    // https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305
убери комменты

2024-09-26 14:04 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/controller/MessageController.java
> +            @RequestParam @Schema(example = "0") long pageNumber,
Maks Molch, [26.09.2024 17:00]
Я решил что не буду Pageable в контроллере принимать

Maks Molch, [26.09.2024 17:02]
Во первых в свагере отображается в виде куска говна - которое хз как починить

Maks Molch, [26.09.2024 17:02]
Во вторых зависимость от фреймворка на presentation слой уходит в виде Pageable

Maks Molch, [26.09.2024 17:02]
Поэтому оставляю как есть

2024-09-26 14:08 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/dto/response/Page.java
> +public record Page<T>(
Чтобы не было зависимости от "стандартных" jpa сущностей (они из jpa, а не из java.util)

2024-09-26 14:13 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/dto/response/message/Payload.java
> +package ru.random.walk.chat_service.dto.response.message;
Не, в папке /message лежит всё что относится к Message, а в папке /message/payload лежит всё что относится к Payload
Payload относится к Message, а не к самому себе

2024-09-27 09:54 UTC, kryakobess approved these changes

2024-09-27 16:07 UTC, merged