RANDOMWALK-61: chat history
ru-random-walk/chat-service pull request #8
Opened 2024-11-03 01:53 UTC by maksmolchdmitr

2024-11-03 11:20 UTC, kryakobess requested changes

2024-11-03 11:20 UTC, kryakobess commented on src/main/resources/application.yaml
> +    password: ${RANDOM_WALK_POSTGRES_PASSWORD:postgres}
Добавь еще сюда указание схемы, чтобы в коде сущностей на нее не ссылаться

2024-11-03 11:20 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/controller/advice/GlobalControllerAdvice.java
> +                                .orElse("...")
И че за три точки? Напиши хоть validation exception

2024-11-03 11:20 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/model/domain/PageRequest.java
> +public record PageRequest(
А в чем проблема использовать библиотечный pageable?

2024-11-03 11:20 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/model/entity/Message.java
> +    @JoinColumn(name = "chat_id", referencedColumnName = "id")
Тебе нужно чтобы при каждом вызове месседжа тянулся eagerly чат к нему? Почему не используешь OneToMany связь в Chat сущности?

2024-11-03 11:20 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/repository/ChatMemberRepository.java
> +    List<ChatMember> findPageByUserId(UUID userId, Pageable pageable);
Он разве с пагинацией тебе ответ вернет? У пагинации же свое Дто Page в ответе. Мне кажется, что вся эта история с пагинацией это велосипед-костыль для сваггера...

2024-11-03 11:20 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/service/ChatService.java
> +import ru.random.walk.chat_service.model.dto.response.Chat;
Переназови в ChatDto, а то у тебя сущность и дто одинаково называются. Это понимание кода ухудшает

2024-11-03 11:27 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/controller/advice/GlobalControllerAdvice.java
> +    @ExceptionHandler(AuthenticationException.class)
Действительно - спасибо

2024-11-03 11:30 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/model/entity/Chat.java
> +@Data
В случае если я захочу их логировать, то думаю просто можно будет переопределить toString() самому
А так пока лучше 1 аннотацию вместо стопитсот

2024-11-03 11:52 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/model/entity/Message.java
> +    private String payload;
Там куча кода нужно для этого сделать - поэтому лучше сделаю в ветке RANDOMWALK-61-message-history

2024-11-03 11:54 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/model/entity/Chat.java
> +@Data
У тебя здесь и так уже 100500 аннотаций, если ты одну заменишь на две ничего не изменится. Тебе все равно придется переопределять equals and hashcode в случае чего, поэтому от даты никакого прока

2024-11-03 11:54 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/model/domain/PageRequest.java
> +public record PageRequest(
Тогда будут проблемы со свагером(

2024-11-03 11:55 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/model/domain/PageRequest.java
> +public record PageRequest(
Pageable в свагере криво работает и как дтошка идёт

2024-11-03 12:02 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/repository/ChatMemberRepository.java
> +    List<ChatMember> findPageByUserId(UUID userId, Pageable pageable);
Тут ещё проблема в том что entity с EmbeddedId - посмотри на ChatMember
Поэтому приходится для этого query писать

2024-11-03 12:03 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/repository/ChatMemberRepository.java
> +    List<ChatMember> findPageByUserId(UUID userId, Pageable pageable);
Но на счёт пагинации проверю работает ли - и исправлю если не будет работать

2024-11-03 12:16 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/model/entity/Chat.java
> +@Data
Твое нежелание писать лишние аннотации в будущем может стрельнуть лишними запросами

2024-11-03 12:18 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/model/entity/Message.java
> +    private String payload;
Тогда сделай более подходящим типом данных -- Map

2024-11-03 12:20 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/service/ChatService.java
> +import ru.random.walk.chat_service.model.dto.response.Chat;
Ухудшает в каком месте?

2024-11-03 12:23 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/model/domain/PageRequest.java
> +public record PageRequest(
Не хочу подстраиваться под сваггер

2024-11-03 12:23 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/model/domain/PageRequest.java
> +public record PageRequest(
Костылить ради него в коде, делать непрозрачные решения

2024-11-03 12:26 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/service/ChatService.java
> +import ru.random.walk.chat_service.model.dto.response.Chat;
У тебя потом еще не даст импорты делать так как названия одинаковые

2024-11-03 18:45 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/model/entity/Chat.java
> +@Data
Стрельнуть может, но я же я объяснил что в этом случае просто переопределю toString()
Также как всё равно придется переопределять equals and hashcode

2024-11-03 18:48 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/model/entity/Message.java
> +    private String payload;
Да я пока ещё не разобрался что там будет - просто удалю тогда для этого PR payload и всё - а в следующем уже напишу как надо

2024-11-03 18:53 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/service/ChatService.java
> +import ru.random.walk.chat_service.model.dto.response.Chat;
> Читаемость. Я пока читал этот код я не понимал ты сущность в page засовываешь или дто

Так тут же явно есть маппинг из сущности в dto:
`                .map(chatMember -> new Chat(chatMember.getId().getChatId()))
`

2024-11-03 18:56 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/service/ChatService.java
> +import ru.random.walk.chat_service.model.dto.response.Chat;
> У тебя потом еще не даст импорты делать так как названия одинаковые

А в этих случаях как раз будет использоваться нейминг с путём, типа `dto.response.Chat` и `entity.Chat`
Довольно таки понятно и читаемо

2024-11-03 18:59 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/model/domain/PageRequest.java
> +public record PageRequest(
Окей, ща - переделаю
Из плюсов: кода меньше станет и сортировка оптом добавиться

2024-11-03 19:10 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/model/domain/PageRequest.java
> +public record PageRequest(
> Костылить ради него в коде, делать непрозрачные решения

Тут довольно всё прозрачно есть PageRequest который реализует Pageable и есть Page<T> которая представляет страницу чего-то
Кроме того что сваггер корявит Pageable
Также у Pageable нет нормальной валидации которую я настроил

2024-11-03 19:18 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/model/entity/Chat.java
> +@Data
Это усложнит диагностику проблемы. Твой аргумент не делать этого заключается в том что тебе лень открыть аннотацию?

2024-11-03 19:32 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/chat_service/model/entity/Chat.java
> +@Data
Переопределю toString()

2024-11-03 21:55 UTC, kryakobess requested changes

2024-11-03 21:55 UTC, kryakobess commented on src/main/java/ru/random/walk/chat_service/model/entity/Chat.java
> +    private List<Message> messages;
Ну вот и тут ты уже попадаешь в n+1 при вызове toString, equals и hashcode

2024-11-04 09:09 UTC, kryakobess requested changes

2024-11-04 09:09 UTC, kryakobess commented on src/main/resources/db/migration/V1.0__Init.sql
> +            CREATE TYPE chat.chat_type AS ENUM ('private', 'group');
Предлагаю соблюдать стандарт для названий енамов - все в upper case через SNAKE_CASE, чтобы не возникало проблем с маппингом в коде

2024-11-04 09:09 UTC, kryakobess commented on src/main/resources/db/migration/V1.0__Init.sql
> +            CREATE TYPE chat.message_type AS ENUM ('text', 'request_for_walk');
тут тоже

2024-11-04 14:54 UTC, kryakobess approved these changes

2024-11-04 14:57 UTC, merged